
name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - master
       
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the latest code
    - name: Checkout the code
      uses: actions/checkout@v2

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Adjust version as needed

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        npm install express ejs 

    # Step 4: Copy files to EC2 using SCP
    - name: Copy files to EC2 via SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        source: "/home/runner/work/node-express-hello-world/node-express-hello-world/*"
        target: "/home/ubuntu/myapp"

    # Step 5: Start or Restart the app using PM2
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.2.2
      with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: cd /home/ubuntu/myapp && pm2 start app.js || pm2 restart app.js
